name: PHPUnit

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # Alias 'master' to 'latest'
    name: WP ${{ matrix.wp == 'master' && 'latest' || matrix.wp }} and PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        wp: [ "6.8", "6.9", "7.0", "7.1", "master" ]
        php: [ "8.2", "8.3", "8.4", "8.5" ]
        exclude:
          # WordPress 6.8 does not support PHP 8.5.
          - wp: "6.8"
            php: "8.5"

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install wordpress environment
        run: npm -g install @wordpress/env

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          composer-options: --prefer-dist --no-progress

      - name: Setup wp-env
        run: wp-env start
        env:
          WP_ENV_CORE: WordPress/WordPress#${{ matrix.wp }}
          WP_ENV_PHP_VERSION: ${{ matrix.php }}

      - name: PHPUnit
        run: composer test

      - name: PHPUnit multisite
        run: composer run-script test-multisite
